// modules/apps/product-navigation/product-navigation-simulation-device/src/main/resources/META-INF/resources/js/components/App.tsx
/**
 * SPDX-FileCopyrightText: © 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

import PropTypes from 'prop-types';
import React, {useRef, useState} from 'react';

import {SIZES, Size} from '../constants/sizes';
import Preview from './Preview';
import SizeSelector from './SizeSelector';

import '../../css/main.scss';

interface IProps {
	portletNamespace: string;
}

export default function App({portletNamespace: namespace}: IProps) {
	const [activeSize, setActiveSize] = useState<Size>(SIZES.desktop);

	const previewRef = useRef<HTMLDivElement>(null);

	return (
		<>
			<SizeSelector
				activeSize={activeSize}
				namespace={namespace}
				previewRef={previewRef}
				setActiveSize={setActiveSize}
			/>

			<Preview activeSize={activeSize} previewRef={previewRef} />
		</>
	);
}

App.propTypes = {
	portletNamespace: PropTypes.string.isRequired,
};

// workspaces/liferay-sample-workspace/client-extensions/liferay-sample-custom-element-3/src/app/app.component.ts
/**
 * SPDX-FileCopyrightText: © 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

import {Component, Input} from '@angular/core';

@Component({
	selector: 'app-root',
	templateUrl: './app.component.html',
	styleUrls: ['./app.component.css'],
})
export class AppComponent {
	@Input('title') title = 'liferay-sample-custom-element-3';
}
